
package ru.ifmo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SculptureService", targetNamespace = "http://service.ifmo.ru/", wsdlLocation = "http://localhost:8080/SculptureService?wsdl")
public class SculptureService
    extends Service
{

    private final static URL SCULPTURE_SERVICE_WSDL_LOCATION;
    private final static WebServiceException SCULPTURE_SERVICE_EXCEPTION;
    private final static QName SCULPTURE_SERVICE_QNAME = new QName("http://service.ifmo.ru/", "SculptureService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SculptureService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCULPTURE_SERVICE_WSDL_LOCATION = url;
        SCULPTURE_SERVICE_EXCEPTION = e;
    }

    public SculptureService() {
        super(__getWsdlLocation(), SCULPTURE_SERVICE_QNAME);
    }

    public SculptureService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCULPTURE_SERVICE_QNAME, features);
    }

    public SculptureService(URL wsdlLocation) {
        super(wsdlLocation, SCULPTURE_SERVICE_QNAME);
    }

    public SculptureService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCULPTURE_SERVICE_QNAME, features);
    }

    public SculptureService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SculptureService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SculptureWebService
     */
    @WebEndpoint(name = "SculptureWebServicePort")
    public SculptureWebService getSculptureWebServicePort() {
        return super.getPort(new QName("http://service.ifmo.ru/", "SculptureWebServicePort"), SculptureWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SculptureWebService
     */
    @WebEndpoint(name = "SculptureWebServicePort")
    public SculptureWebService getSculptureWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ifmo.ru/", "SculptureWebServicePort"), SculptureWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCULPTURE_SERVICE_EXCEPTION != null) {
            throw SCULPTURE_SERVICE_EXCEPTION;
        }
        return SCULPTURE_SERVICE_WSDL_LOCATION;
    }

}
