
package ru.ifmo.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "SculptureWebService", targetNamespace = "http://service.ifmo.ru/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface SculptureWebService {


    /**
     * @param q
     * @return returns java.util.List<ru.ifmo.service.Sculpture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSculptures", targetNamespace = "http://service.ifmo.ru/", className = "ru.ifmo.service.FindSculptures")
    @ResponseWrapper(localName = "findSculpturesResponse", targetNamespace = "http://service.ifmo.ru/", className = "ru.ifmo.service.FindSculpturesResponse")
    @Action(input = "http://service.ifmo.ru/SculptureWebService/findSculpturesRequest", output = "http://service.ifmo.ru/SculptureWebService/findSculpturesResponse")
    public List<Sculpture> findSculptures(
            @WebParam(name = "q", targetNamespace = "")
                    MyRequest q);

    /**
     * @return returns java.util.List<ru.ifmo.service.Sculpture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSculptures", targetNamespace = "http://service.ifmo.ru/", className = "ru.ifmo.service.GetAllSculptures")
    @ResponseWrapper(localName = "getAllSculpturesResponse", targetNamespace = "http://service.ifmo.ru/", className = "ru.ifmo.service.GetAllSculpturesResponse")
    @Action(input = "http://service.ifmo.ru/SculptureWebService/getAllSculpturesRequest", output = "http://service.ifmo.ru/SculptureWebService/getAllSculpturesResponse")
    public List<Sculpture> getAllSculptures();

}
